"""
VII Two — Frame types for the voice pipeline.
Inspired by Pipecat's frame-based architecture.
Frames are the unit of communication between pipeline stages.
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Optional
import time


class AgentName(str, Enum):
    BOB = "bob"
    FALCON = "falcon"
    ACE = "ace"
    PIXI = "pixi"
    BUZZ = "buzz"
    CLAUDE = "claude"
    FOUNDER = "founder"


class PipelineState(str, Enum):
    IDLE = "idle"
    LISTENING = "listening"
    THINKING = "thinking"
    SPEAKING = "speaking"
    INTERRUPTED = "interrupted"


@dataclass
class Frame:
    """Base frame type."""
    timestamp: float = field(default_factory=time.time)


# --- Text Frames ---

@dataclass
class TranscriptionFrame(Frame):
    """STT output — transcribed user speech."""
    text: str = ""
    agent: Optional[AgentName] = None  # Dispatched agent (if detected)
    is_final: bool = True


@dataclass
class TextFrame(Frame):
    """LLM output — streaming text chunk."""
    text: str = ""


@dataclass
class SentenceFrame(Frame):
    """Complete sentence extracted from TextFrame stream. Ready for TTS."""
    text: str = ""
    sentence_index: int = 0


# --- Audio Frames ---

@dataclass
class AudioInputFrame(Frame):
    """Raw audio from microphone."""
    audio: bytes = b""
    sample_rate: int = 16000
    channels: int = 1


@dataclass
class AudioOutputFrame(Frame):
    """Audio chunk for playback. Generated by TTS."""
    audio: bytes = b""
    sample_rate: int = 24000
    channels: int = 1
    mouth_sync: list = field(default_factory=list)  # RMS levels at 20Hz
    is_final: bool = False


# --- Control Frames ---

@dataclass
class InterruptionFrame(Frame):
    """Kill current response. User spoke or pressed PTT."""
    reason: str = "user_interrupt"


@dataclass
class StateChangeFrame(Frame):
    """Pipeline state transition."""
    from_state: Optional[PipelineState] = None
    to_state: PipelineState = PipelineState.IDLE
    agent: Optional[AgentName] = None


@dataclass
class AgentSwitchFrame(Frame):
    """Switch active agent."""
    agent: AgentName = AgentName.BOB


# --- Lifecycle Frames ---

@dataclass
class StartFrame(Frame):
    """Pipeline startup."""
    pass


@dataclass
class StopFrame(Frame):
    """Pipeline shutdown."""
    pass


@dataclass
class TTSStartedFrame(Frame):
    """TTS has begun generating audio for a sentence."""
    sentence_index: int = 0


@dataclass
class TTSStoppedFrame(Frame):
    """TTS has finished generating audio for a sentence."""
    sentence_index: int = 0
